Этап 1. Сервис статистики
mynameisSergey/java-explore-with-me pull request #4
Opened 2023-07-14 08:50 UTC by mynameisSergey

2023-07-15 09:07 UTC, Fleaman777 requested changes

2023-07-15 09:07 UTC, Fleaman777 commented on stats-module/stats-dto/src/main/java/ru/practicum/exp/stat/dto/HitDto.java
> +    Long id;
поля должны быть private, если не требуется обратное

аналагично в других местах

2023-07-15 09:07 UTC, Fleaman777 commented on stats-module/stats-server/src/main/java/ru/practicum/exp/stat/serv/services/HitServiceImp.java
> +        log.info("Сохранение информации о запросе " + hitDto.getUri());
в  логгере лучше использовать плейсхолдер {}, 
и работает оптимальней и выглядит чуть аккуратней

2023-07-15 09:07 UTC, Fleaman777 commented on stats-module/stats-server/src/main/java/ru/practicum/exp/stat/serv/services/StatServiceImp.java
> +            log.info("Получение информации о запросе start: {}, end: {}, unique: {}, uris: {}", start, end, true, true);
лог "Получение информации о запросе start: {}, end: {}, unique: {}, uris: {}" можно было бы вынести в константу

2023-07-17 17:48 UTC, mynameisSergey commented on stats-module/stats-server/src/main/java/ru/practicum/exp/stat/serv/services/StatServiceImp.java
> +            log.info("Получение информации о запросе start: {}, end: {}, unique: {}, uris: {}", start, end, true, true);
исправил

2023-07-17 18:08 UTC, mynameisSergey commented on stats-module/stats-dto/src/main/java/ru/practicum/exp/stat/dto/HitDto.java
> +    Long id;
исправил

2023-07-17 18:37 UTC, mynameisSergey commented on stats-module/stats-server/src/main/java/ru/practicum/exp/stat/serv/services/HitServiceImp.java
> +        log.info("Сохранение информации о запросе " + hitDto.getUri());
исправил. Спасибо за ревью!

2023-07-18 15:33 UTC, Fleaman777 requested changes

2023-07-18 15:33 UTC, Fleaman777 commented on stats-module/stats-client/src/main/java/ru/practicum/exp/stat/client/StatsClient.java
> +    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_TIME_FORMAT);
по джава код стайлу уонстанта должна называться в верхнем регистре

2023-07-18 15:33 UTC, Fleaman777 commented on stats-module/stats-dto/src/main/java/ru/practicum/exp/stat/dto/ViewStatsDto.java
> +    String app;
поля должны быть private, если не требуется обратное

2023-07-18 15:33 UTC, Fleaman777 commented on stats-module/stats-server/src/main/java/ru/practicum/exp/stat/serv/util/DateFormatter.java
> +    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
аналогично

2023-07-20 18:40 UTC, merged