Этап 2. Основной сервис
mynameisSergey/java-explore-with-me pull request #5
Opened 2023-07-20 19:56 UTC by mynameisSergey

2023-07-21 15:05 UTC, Fleaman777 requested changes

2023-07-21 15:05 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/models/Compilation.java
> +    @Column(name = "pinned")
если названия параметра name совпадает с названием поля, то можно не указывать аннотацию, 
что в целом хорошо, т.к. будет меньше кода, меньше отвлекающих факторов, 
к тому же, если все таки где-то название колонки не будет совпадать с названием поля, то мы это точно не пропустим, т.к. у нас аннотация Column будет висеть только в тех местах, где это действительно необходимо

2023-07-21 15:05 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/models/dto/EventFullDto.java
> +    String annotation;
поля должны быть private

аналогично в других местах

2023-07-21 15:05 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/services/implementation/EventAdminServiceImp.java
> +        } else if (stateAction.equals(ActionState.CANCEL_REVIEW)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, правильней, и выглядит чуть очевидней

2023-07-21 15:05 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/services/implementation/EventPublicServiceImp.java
> +    public EventFullDto get(Long id, HttpServletRequest request) {
get слишком общее название, хорошо было бы его как-нибудь уточнить

2023-07-23 19:22 UTC, mynameisSergey commented on main-service/src/main/java/ru/practicum/models/dto/EventFullDto.java
> +    String annotation;
исправил

2023-07-23 19:29 UTC, mynameisSergey commented on main-service/src/main/java/ru/practicum/services/implementation/EventPublicServiceImp.java
> +    public EventFullDto get(Long id, HttpServletRequest request) {
исправил

2023-07-23 19:35 UTC, mynameisSergey commented on main-service/src/main/java/ru/practicum/services/implementation/EventAdminServiceImp.java
> +        } else if (stateAction.equals(ActionState.CANCEL_REVIEW)) {
переделал

2023-07-23 19:40 UTC, mynameisSergey commented on main-service/src/main/java/ru/practicum/models/Compilation.java
> +    @Column(name = "pinned")
исправил

2023-07-23 19:45 UTC, mynameisSergey commented on main-service/src/main/java/ru/practicum/exceptions/ErrorHandlerMain.java
> +    }
Привет. Если ты не против, я оставил бы это как есть. Спасибо за ревью! Хорошие замечания! Хоть эти ошибки и очевидны, но без тебя я не обратил на них внимания. Теперь код стал чище))

2023-07-24 08:38 UTC, Fleaman777 approved these changes

2023-07-24 08:38 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/models/dto/LocationDto.java
> +    float lon;
тут забыл про private

2023-07-24 08:38 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/models/dto/ParticipationRequestDto.java
> +    String status;
и тут

и в других похожих местах

2023-07-27 21:33 UTC, merged